Add latest add-ons
uploadcare/uploadcare-android pull request #97
Opened 2023-11-09 12:37 UTC by CheK539

Closes https://github.com/uploadcare/uploadcare-android/issues/87

2023-11-09 17:47 UTC, rsedykh requested changes

2023-11-09 17:47 UTC, rsedykh commented on CHANGELOG.md
> +  - Added support for latest add-ons.
```suggestion
  - Added support for [object recognition](https://uploadcare.com/docs/intelligence/object-recognition/), [unsafe content detection](https://uploadcare.com/docs/unsafe-content/), [malware protection](https://uploadcare.com/docs/security/malware-protection/), and [background removal](https://uploadcare.com/docs/remove-bg/).
```

2023-11-09 17:47 UTC, rsedykh commented on documentation/LIBRARY.md
> +Java
```suggestion

Java
```

2023-11-09 17:47 UTC, rsedykh commented on documentation/LIBRARY.md
> +Java
```suggestion

Java
```

2023-11-09 17:47 UTC, rsedykh commented on documentation/LIBRARY.md
> +Java
```suggestion

Java
```

2023-11-09 17:47 UTC, rsedykh commented on documentation/LIBRARY.md
> +Java
```suggestion

Java
```

2023-11-09 17:47 UTC, rsedykh commented on documentation/LIBRARY.md
> +Java
```suggestion

Java
```

2023-11-09 17:47 UTC, rsedykh commented on documentation/LIBRARY.md
> +Java
```suggestion

Java
```

2023-11-09 17:47 UTC, rsedykh commented on documentation/LIBRARY.md
> +Java
```suggestion

Java
```

2023-11-09 17:47 UTC, rsedykh commented on documentation/LIBRARY.md
> +Java
```suggestion

Java
```

2023-11-12 20:37 UTC, rsedykh submitted a review, later dismissed

2023-11-13 13:44 UTC, rsedykh submitted a review, later dismissed

2023-11-13 14:22 UTC, onthecrow approved these changes

2023-11-13 14:23 UTC, merged