Add rules for Proguard
uploadcare/uploadcare-android pull request #98
Opened 2023-11-13 14:13 UTC by CheK539

Fixes https://github.com/uploadcare/uploadcare-android/issues/49

2023-11-14 11:26 UTC, onthecrow submitted a review, later dismissed

2023-11-15 06:53 UTC, onthecrow approved these changes

2023-11-15 13:51 UTC, rsedykh requested changes

2023-11-15 13:51 UTC, rsedykh commented on CHANGELOG.md
> +  - Added keep DTO classes to Proguard's rules, as network JSON Adapter uses reflection on them.
```suggestion
  - Added Proguard rule to keep DTO classes to avoid issues with network JSON deserialization.
```

2023-11-15 13:51 UTC, rsedykh commented on CHANGELOG.md
> +  - Added keep DTO classes to Proguard's rules, as network JSON Adapter uses reflection on them.
```suggestion
  - Added Proguard rule to keep DTO classes to avoid issues with network JSON deserialization.
```

2023-11-15 13:52 UTC, rsedykh approved these changes

2023-11-15 15:54 UTC, merged